- name: PLAY1
  hosts: local
  connection: local
  task:
  - name: PLAY1 and TASK1
    ansible.builtin.debug:
      msg: "Hello from PLAY1 and TASK1"
- name: PLAY2
  hosts: local
  connection: local
  task:
  - name: PLAY1 and TASK1
    ansible.builtin.debug:
      msg: "Hello from PLAY2 and TASK2"    